using BillingApp.API.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BillingApp.API.Services;

public class PdfService : IPdfService
{
    public PdfService()
    {
        // License setup (Community License)
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GenerateInvoicePdf(Bill bill)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1, Unit.Centimetre);
                page.PageColor(Colors.White);
                
                // Using a more professional font if available, fallback to Lato/Inter style
                page.DefaultTextStyle(x => x.FontSize(10).FontFamily(Fonts.Verdana));

                page.Header().Element(ComposeHeader);
                page.Content().Element(ComposeContent);
                
                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by BillPro • Page ");
                    x.CurrentPageNumber();
                });
            });
        }).GeneratePdf();

        void ComposeHeader(IContainer container)
        {
            var titleStyle = TextStyle.Default.FontSize(24).ExtraBold().FontColor(Colors.Blue.Medium);

            container.PaddingBottom(20).Row(row =>
            {
                row.RelativeItem().Column(column =>
                {
                    column.Item().Text(bill.ShopOwner?.ShopName?.ToUpper() ?? "YOUR BUSINESS").Style(titleStyle);
                    
                    column.Item().PaddingTop(5).Column(col => {
                        if (!string.IsNullOrEmpty(bill.ShopOwner?.Address))
                            col.Item().Text(bill.ShopOwner.Address).FontSize(9).FontColor(Colors.Grey.Medium);
                        
                        if (!string.IsNullOrEmpty(bill.ShopOwner?.GSTIN))
                             col.Item().Text($"GSTIN: {bill.ShopOwner.GSTIN}").FontSize(9).SemiBold();
                    });
                });

                row.ConstantItem(150).Column(column =>
                {
                    column.Item().AlignRight().Text("TAX INVOICE").FontSize(20).SemiBold().FontColor(Colors.Grey.Darken2);
                    column.Item().AlignRight().Text($"# {bill.BillNumber}").FontSize(12).SemiBold();
                    column.Item().AlignRight().Text($"Date: {bill.Date:dd-MMM-yyyy}").FontSize(10);
                });
            });
        }

        void ComposeContent(IContainer container)
        {
            container.PaddingVertical(10).Column(column =>
            {
                // Billing Info Row
                column.Item().PaddingBottom(20).Row(row =>
                {
                    row.RelativeItem().Border(1).BorderColor(Colors.Grey.Lighten3).Padding(10).Column(col => {
                        col.Item().Text("BILL TO").FontSize(8).SemiBold().FontColor(Colors.Grey.Medium);
                        col.Item().Text(bill.Customer?.Name ?? "Walk-in Customer").FontSize(12).SemiBold();
                        col.Item().Text(bill.Customer?.Mobile ?? "").FontSize(10);
                        col.Item().Text(bill.Customer?.Address ?? "").FontSize(9).FontColor(Colors.Grey.Darken1);
                    });
                    
                    row.ConstantItem(20); // Spacer
                    
                    row.RelativeItem().Column(col => {
                        // Optional Place for Logo or Shop Contact
                        col.Item().AlignRight().Text("Contact").FontSize(8).SemiBold().FontColor(Colors.Grey.Medium);
                        col.Item().AlignRight().Text("support@billpro.com").FontSize(10);
                    });
                });

                // Table
                column.Item().Element(ComposeTable);
                
                // Totals
                column.Item().PaddingTop(20).AlignRight().Table(table => {
                    table.ColumnsDefinition(cols => {
                        cols.RelativeColumn();
                        cols.ConstantColumn(100);
                    });
                    
                    table.Cell().Text("Subtotal").AlignRight();
                    table.Cell().AlignRight().Text($"{bill.SubTotal:N2}");
                    
                    table.Cell().Text("CGST (9%)").AlignRight();
                    table.Cell().AlignRight().Text($"{bill.TotalCGST:N2}");
                    
                    table.Cell().Text("SGST (9%)").AlignRight();
                    table.Cell().AlignRight().Text($"{bill.TotalSGST:N2}");
                    
                    table.Cell().PaddingTop(5).Text("Grand Total").AlignRight().SemiBold().FontSize(14);
                    table.Cell().PaddingTop(5).BorderTop(1).AlignRight().Text($"INR {bill.TotalAmount:N2}").SemiBold().FontSize(14).FontColor(Colors.Blue.Medium);
                });

                // Terms
                column.Item().PaddingTop(40).Column(col => {
                    col.Item().Text("Terms & Conditions").FontSize(8).SemiBold();
                    col.Item().Text("1. Goods once sold will not be taken back.").FontSize(7).FontColor(Colors.Grey.Medium);
                    col.Item().Text("2. This is a computer generated invoice.").FontSize(7).FontColor(Colors.Grey.Medium);
                });
            });
        }

        void ComposeTable(IContainer container)
        {
            container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(30);
                    columns.RelativeColumn(4);
                    columns.RelativeColumn(2);
                    columns.RelativeColumn(2);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(2);
                });

                table.Header(header =>
                {
                    header.Cell().Element(CellStyle).Text("#");
                    header.Cell().Element(CellStyle).Text("Description");
                    header.Cell().Element(CellStyle).Text("HSN/SAC");
                    header.Cell().Element(CellStyle).AlignRight().Text("Rate");
                    header.Cell().Element(CellStyle).AlignCenter().Text("Qty");
                    header.Cell().Element(CellStyle).AlignRight().Text("Amount");

                    static IContainer CellStyle(IContainer container) => container.DefaultTextStyle(x => x.SemiBold()).PaddingVertical(8).BorderBottom(1).BorderColor(Colors.Grey.Darken2).Background(Colors.Grey.Lighten4).PaddingLeft(5);
                });

                foreach (var item in bill.Items)
                {
                    var index = bill.Items.IndexOf(item) + 1;
                    table.Cell().Element(CellStyle).Text(index.ToString());
                    table.Cell().Element(CellStyle).Text(item.ItemName);
                    table.Cell().Element(CellStyle).Text(item.HSNCode ?? "-");
                    table.Cell().Element(CellStyle).AlignRight().Text(item.Price.ToString("N2"));
                    table.Cell().Element(CellStyle).AlignCenter().Text(item.Quantity.ToString());
                    table.Cell().Element(CellStyle).AlignRight().Text(item.Total.ToString("N2"));

                    static IContainer CellStyle(IContainer container) => container.BorderBottom(1).BorderColor(Colors.Grey.Lighten3).PaddingVertical(6).PaddingLeft(5);
                }
            });
        }
    }
    
    public class AddressComponent : IComponent
    {
        private string Title { get; }
        private string Name { get; }
        private string Address { get; }

        public AddressComponent(string title, string name, string address)
        {
            Title = title;
            Name = name;
            Address = address;
        }

        public void Compose(IContainer container)
        {
            container.Column(column =>
            {
                column.Spacing(2);

                column.Item().BorderBottom(1).PaddingBottom(5).Text(Title).SemiBold();
                column.Item().Text(Name);
                column.Item().Text(Address);
            });
        }
    }
}
